language: node_js

node_js:
    - "6.1"

# whitelisted branches
branches:
    only:
        - master

before_install:
    - npm install -g eslint
    - npm install

script:
    - npm run lint
    - npm run test
